feat: Break render islands single task into to multiples
freshframework/fresh pull request #1019
Opened 2023-02-06 15:28 UTC by igorbrasileiro

# Pull Request Context
The fresh hydration runs inside a single tasks, that means all plugins and all islands js execution will run in one tasks and probably will create a long task. Long Task, following the google definition, is every task the takes more than 50ms. This behavior impacts the total blocking time (TBT) and the Time to Interactive (TTI) metrics from Lighthouse (LH)

This algorithm increase linearly with the number of plugins/islands

## What this Pull Request does?
Knowing the problem above, this pull request suggest breaking the revive function task, that render all islands, into multiple tasks, one by island using the scheduler.postTask api or to setTimeout zero as fallback. Here a reference about "breaking long tasks" https://web.dev/optimize-long-tasks/
 What's the benefit of this:
1. for each island the browser creates a task, so, each island has 50ms additional time, this impact directly the TBT and TTI;
2. Also, browsers that implements the scheduler, can prioritize user interaction over hydration/revive, and this gives the site user a better user experience;

> ⚠️ This changes could run under an experimental flag, but I don't know what's the best approach to do this. I left a TODO warning about it.

## Results
I ran 30 PageSpeed Insights test via API, using https://github.com/igorbrasileiro/psi-sample-test, for each deploy preview with strategy mobile.

Example 1:
Before the change: https://deco-sites-fashion-xpv2mkxz84gg.deno.dev/
| Metric | Mean | Standard deviation | Confidence Interval (95%) |
|--------|--------|--------|--------|
| Cumulative Layout shift (CLS) | 0.00 | 0.00 | [0.00, 0.00] |
| First Contentful Paint (FCP) | 1836.81 | 1.43 | [1836.30, 1837.32] |
| Largest Contentful Paint (LCP) | 2201.81 | 39778.79 | [-12032.84, 16436.47] |
| Time to Interactive (TTI) | 2123.17 | 14203.80 | [-2959.59, 7205.94] |
| Total Blocking Time (TBT) | 184.18 | 6179.87 | [-2027.26, 2395.62] |
| Performance score | 0.916 | 0.002511 | [0.914768, 0.916565] |
| JavaScript Execution Time | 719.95 | 23649.72 | [-7742.99, 9182.90] |
| Speed Index | 4085.94 | 5382052.26 | [-1921856.72, 1930028.61] |

After the change: https://deco-sites-fashion-pmxene9e23eg.deno.dev/
| Metric | Mean | Standard deviation | Confidence Interval (95%) |
|--------|--------|--------|--------|
| Cumulative Layout shift (CLS) | 0.00 | 0.00 | [0.00, 0.00] |
| First Contentful Paint (FCP) | 1836.14 | 0.00 | [1836.14, 1836.14] |
| Largest Contentful Paint (LCP) | 2136.14 | 0.00 | [2136.14, 2136.14] |
| Time to Interactive (TTI) | 2087.71 | 27.62 | [2077.83, 2097.59] |
| Total Blocking Time (TBT) | 108.10 | 164.64 | [49.18, 167.02] |
| Performance score | 0.963 | 0.000021 | [0.962992, 0.963008] |
| JavaScript Execution Time | 665.85 | 566.01 | [463.30, 868.39] |
| Speed Index | 2656.46 | 238907.39 | [-82835.45, 88148.37] |

As you can see, the TTI and TBT the mean is lower and the std deviation too.

## References
https://web.dev/optimize-long-tasks/
https://web.dev/tbt/
https://pagespeed.web.dev/
https://github.com/igorbrasileiro/psi-sample-test

2023-02-06 15:34 UTC, igorbrasileiro commented
The project and deploy preview used as example comes from https://github.com/deco-sites/fashion/pull/46

2023-02-06 17:11 UTC, igorbrasileiro commented
The flamegraph differences
before the change: you can see one task for the plugins + revive + render islands
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/15680320/217037769-03b7ead1-a81d-4fcc-bfc3-007e7755c445.png">

after the change: you can see one task for plugins + revive and other small tasks for render the islands 
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/15680320/217037503-86caa605-3611-4feb-b7a3-d12a0697e5f7.png">

2023-02-28 21:12 UTC, guifromrio commented
@lucacasonato @ry sorry to bother — did you get a chance to look at this one? We understand it's a low hanging fruit which could help our PageSpeed performance a bit.

2023-03-30 13:45 UTC, tlgimenes commented
Hey folks, any news on this one? This seems to be a free lunch in terms of lighthouse scores.

2023-06-05 06:15 UTC, iuioiua requested changes

2023-06-05 06:15 UTC, iuioiua commented on src/runtime/main.ts
> +      // TODO: Run this under a flag
```suggestion
```
I think this is fine to run without a flag.

2023-06-05 06:15 UTC, iuioiua commented on src/runtime/main.ts
> +      };
```suggestion
      function _render() {
        render(
          h(islands[id], props[Number(n)]),
          createRootFragment(
            parent! as HTMLElement,
            children,
            // deno-lint-ignore no-explicit-any
          ) as any as HTMLElement,
        );
      }
```
Nit: arrow functions are only really used with anonymous functions in this codebase.

2023-06-05 06:26 UTC, iuioiua commented on src/runtime/main.ts
> +      };
Could you please also resolve the merge conflict?

2023-06-05 06:40 UTC, iuioiua commented
Note: [`scheduler.postTask()` is well-supported, at 70% of all users](https://caniuse.com/mdn-api_scheduler_posttask). My only concern is the backup use of `setTimeout()`, which could impede performance for a large number of islands. However, the benefit of doing so will likely outweigh any headaches, so +1 from me.

If I'm wrong, alternatively, we can instead have the backup function be the old-fashioned `_render()`.

2023-06-06 21:57 UTC, iuioiua approved these changes
I've made the suggested changes, except for turning `_render()` into a normal function to avoid a lint error. Now, LGTM! Thanks, @igorbrasileiro.

2023-06-07 10:30 UTC, lucacasonato approved these changes
LGTM

2023-06-07 10:32 UTC, merged

2023-06-08 19:36 UTC, guifromrio commented
Great work @igorbrasileiro, thanks for the kind attention @iuioiua and @lucacasonato !