fix: don't change scheme on redirect
freshframework/fresh pull request #1024
Opened 2023-02-10 21:44 UTC by lucacasonato

2023-05-03 19:33 UTC, hashrock approved these changes
LGTM!

2023-05-22 05:24 UTC, iuioiua requested changes
`cleanPathname()` from this file can also be removed.

2023-05-22 05:24 UTC, iuioiua commented on src/server/context.ts
> +        const path = url.pathname.slice(0, -1);
```suggestion
        // Remove trailing slashes
        const path = url.pathname.replace(/\/+$/, "");
```

2023-05-25 08:01 UTC, hashrock approved these changes
LGTM!

2023-05-25 08:40 UTC, iuioiua approved these changes

2023-05-25 08:40 UTC, merged