docs: Carousel Component
freshframework/fresh pull request #1096
Opened 2023-03-31 17:41 UTC by digitaldesigndj

Carousel Component added to the site as requested in Pull Request #1088

2023-03-31 19:14 UTC, digitaldesigndj commented
When I do `deno check main.ts dev.ts` locally it seemed to be using more lenient settings... I worked it out using the actions, but why is more strict on actions? (example I can't use type :any on the action)

2023-04-07 09:29 UTC, hashrock commented on www/components/gallery/Carousel.tsx
> +    document.addEventListener("keydown", keydownHandler);
We might want it to respond to arrow keys only when this component has focus

2023-04-07 09:30 UTC, hashrock requested changes
Looks great!

2023-04-08 01:37 UTC, digitaldesigndj commented
I don't think I know how to do that without adding a while bunch of code, and I don't think that really fits with the spirit of what I was trying for. How about I just remove the keyboard listeners altogether?

2023-04-08 01:45 UTC, digitaldesigndj commented
So the way I see to make this work is to add another signal "focused" then I have to toggle that value with the `onBlur` and `onFocus` events. Then I check "focused" in my keyboard handler and take action from there.

Is there is a simpler way I am missing? `document.activeElement` doesn't seem to do the thing I am thinking of.

2023-04-08 07:08 UTC, hashrock commented
how about this?

- add `tabindex=0` to element
- addEventListener to element instead of document

2023-04-17 13:25 UTC, hashrock commented
hmm, I think it doesn't need to use signal.
do you think we can use useState instead?

2023-04-18 01:59 UTC, digitaldesigndj commented
I think there is a bug in the way I did the useState. My first idea is to make it just a fade transition instead of a Carousel, I have to backtrack a bit to figure out how to use the different state API.

Also, I am trying to understand what the use of the useSignal hook is if you prefer useState in components? I like signals because the API is cleaner IMHO, is there more than that to it?

2023-04-18 04:20 UTC, hashrock commented
Oh sorry, I thought that signals was only used for communication between islands. But the preact docs show such as usecase for local state.
https://preactjs.com/guide/v10/signals/

If that's why you prefer the signals API, then I guess you can just use signals here.

2023-04-26 19:50 UTC, hashrock approved these changes
LGTM

2023-04-26 19:51 UTC, merged