Add document test with createHandler AND example
freshframework/fresh pull request #1223
Opened 2023-05-30 15:26 UTC by Octo8080X

Fixes [#1222](https://github.com/denoland/fresh/issues/1222)

Add example implementation and documentation of test code using `createHandler()` newly added by [#622](https://github.com/denoland/fresh/pull/622)

2023-05-30 23:31 UTC, iuioiua commented
Hi, @Octo8080X. Apologies, I wasn't clear enough that we'd like this in the new examples section of the documentation. It'll only require snippets, which will mean less maintenance in the future. Can you rework this as a `/docs/examples/testing.md` (or similar) file?

Also, could you please use Deno's Standard Library for assertion functions? You can check it out [here](https://deno.land/std@0.190.0/testing/asserts.ts?doc=).

2023-05-31 03:13 UTC, Octo8080X commented
Hi, @iuioiua san.

> Can you rework this as a /docs/examples/testing.md (or similar) file?

OK. `/docs/getting-started/create-test.md`, I'll let `/docs\examples\testing.md` remake it.

> Also, could you please use Deno's Standard Library for assertion functions?

I am sorry, but I used `assertEquals` that existed in `https://deno.land/std@0.190.0/testing/asserts.ts`. Was it insufficient?
If you don't want me to assume an import map, or if you mean that you don't want me to use superdeno and deno_dom, please let me know.

2023-05-31 03:19 UTC, iuioiua commented
> OK. `/docs/getting-started/create-test.md`, I'll let `/docs\examples\testing.md` remake it.
> 
> >

👍🏾 

> If you don't want me to assume an import map, or if you mean that you don't want me to use superdeno and deno_dom, please let me know.

Yeah, I think just using assertions from `std` is good enough. I don't think superdeno and deno_dom are needed.

2023-05-31 04:34 UTC, Octo8080X commented
@iuioiua san
Thanks for letting me know.

Removed dependencies on superdeno and deno_dom and moved documents.
Please check.

2023-05-31 06:37 UTC, iuioiua requested changes
Can you please delete everything outside of the `docs/examples` folder?

A few other notes:
- Are you able to reduce some of the spacing between lines? It seems a bit too spread out.
- I think we can remove the last test step.
- Check out https://github.com/denoland/fresh/blob/main/tests/main_test.ts if you'd like some guidance.

2023-05-31 06:37 UTC, iuioiua commented on docs/examples/testing.md
> +```
I think we can remove this.

2023-05-31 06:37 UTC, iuioiua commented on docs/examples/testing.md
> +    const handler = await createHandler(manifest);
`handler` can be moved to the start of the test and only declared once, instead at every test step.

2023-05-31 06:37 UTC, iuioiua commented on docs/examples/testing.md
> +// examples\test\test\main_test.ts
```suggestion
// tests/main_test.ts
```

2023-05-31 13:24 UTC, Octo8080X commented
I missed the instruction to delete examples. My apologies.
I was able to delete it.
(Only docs/examples/testing.md was added.)

I would appreciate it if you could check my remarks to test code, as I have also reflected them.

2023-06-06 12:15 UTC, iuioiua approved these changes
I've made a few tweaks. Now, LGTM!

Note: do not merge this until the next release is cut, as `createHandler()` is not yet part of the API.

2023-06-06 12:21 UTC, iuioiua commented
On second thought, this might belong in the "Concepts" section instead of "Examples"...

2023-06-12 11:02 UTC, lucacasonato approved these changes
I think this being in the "Examples" section is ok. Thanks!

2023-06-12 21:37 UTC, merged

2023-06-12 21:42 UTC, iuioiua commented
Ah, I should have followed my own advice and merged this after the next release was cut. Hopefully, this doesn't cause too much headache, as the new release is being published soon. Apologies. My bad.