Example on using <Head />
freshframework/fresh pull request #1226
Opened 2023-05-31 00:24 UTC by DanielXing1103

resolves #1215 by adding example on modifying ``` <Head />``` on index.md

2023-05-31 00:40 UTC, iuioiua requested changes
I like the conciseness of this. Though, I think the title should be "Modifying the `<head />` Element" and the example should have its own `modifying-the-head-element.md` file in the `/docs/examples` folder. We can provide a link to the page on the examples page like https://deno.com/manual@v1.34.1/examples

2023-05-31 04:07 UTC, DanielXing1103 commented
Thank you very much for the feedback. Just to clarify, is the example in this PR the one mentioned in #1215?

2023-05-31 04:21 UTC, iuioiua commented
> Just to clarify, is the example in this PR the one mentioned in #1215?

Yes, it is 👍🏾

2023-05-31 05:12 UTC, iuioiua commented on docs/examples/modifying-the-head-element.md
> +# Modifying Web Page Metadata via the ```<Head /> ```Element
```suggestion
# Modifying Web Page Metadata via the `<Head />` Element
```
Triple backticks aren't needed for inline code snippets. Can you please use a single backtick where appropriate?

2023-05-31 06:20 UTC, iuioiua requested changes
Few thoughts:
- The article should have the paragraph text come first, then the snippet last.
- Can we provide a short list of some common uses for modifying the `<head>` element?
- The `<Head />` component only includes a `<title>` element. Can we add a few more common use cases, such as meta tags, script, etc.?

2023-05-31 06:20 UTC, iuioiua commented on docs/examples/modifying-the-head-element.md
> +import { Head } from "$fresh/runtime.ts";
```suggestion
// routes/index.tsx
import { Head } from "$fresh/runtime.ts";
```

2023-05-31 06:20 UTC, iuioiua commented on docs/examples/image/Head.png
This image is not needed.

2023-05-31 08:33 UTC, lucacasonato commented on docs/examples/modifying-the-head-element.md
> +        <Counter start={3} />
```suggestion
        <h1>Hello World</h1>
```

This part of the example is not important to what we are trying to bring across, so we can simplify. This allows users to focus on the important bit (the `<Head>` tag).

2023-06-01 01:35 UTC, iuioiua requested changes

2023-06-01 01:35 UTC, iuioiua commented on docs/examples/index.md
> +- [Modifying Web Page Metadata via the `<head>` Element](modifying-the-head-element.md)
```suggestion
- [Modifying the `<head>` Element](modifying-the-head-element.md)
```

2023-06-01 01:35 UTC, iuioiua commented on docs/examples/modifying-the-head-element.md
> +add a new components to the `<head />` element of the display page.
```suggestion
add a new components to the `<head>` element of the display page.
```

2023-06-01 01:35 UTC, iuioiua commented on docs/examples/modifying-the-head-element.md
> +- `<script>` reference JavaScript code
```suggestion
## Common uses for modifying `<head>`

- Setting the document title using `<title>`
- Specifying page metadata using `<meta>`
- Linking to external resources using `<link>`
- Including JavaScript code via `<script>`
```

2023-06-02 14:34 UTC, lucacasonato approved these changes
Great, TY!

2023-06-02 23:55 UTC, iuioiua approved these changes
LGTM! Thanks, @DanielXing1103.

2023-06-02 23:56 UTC, merged

2023-06-03 02:52 UTC, DanielXing1103 commented
Thank you very much for the help along the way.