feat(server): trailing slash configuration
freshframework/fresh pull request #1291
Opened 2023-06-14 16:05 UTC by deer

closes https://github.com/denoland/fresh/issues/359
supersedes https://github.com/denoland/fresh/pull/433

Once again standing on the shoulders of giants here (i.e. I took the solution from 433). I tried adding some documentation for configuring the server as well.

2023-06-14 16:08 UTC, deer commented
Is there any way for me to retrigger certain checks?

2023-06-15 04:45 UTC, iuioiua requested changes
Thanks for adding the test!

Keen to see the server configuration added. But can you please create a separate PR for it?

2023-06-15 04:45 UTC, iuioiua commented on src/server/types.ts
> +   *  @default [false]
```suggestion
   *  @default {false}
```
The `@default` tag takes curly braces. Example [here](https://deno.land/std@0.191.0/async/mod.ts?s=DelayOptions).

Could you please add a small description for this property too?

2023-06-15 04:56 UTC, deer commented
> Thanks for adding the test!
> 
> Keen to see the server configuration added. But can you please create a separate PR for it?

Sorry, what do you mean? Which stuff should stay here then?

2023-06-15 04:58 UTC, iuioiua commented on docs/concepts/server-configuration.md
To clarify, this file should be part of a separate PR.

2023-06-15 05:05 UTC, deer commented on docs/concepts/server-configuration.md
Sure, I thought it would be good to introduce documentation for this new feature at the time I was introducing it, but if you want a separate PR I can do that.

2023-06-15 05:09 UTC, iuioiua commented on docs/concepts/server-configuration.md
Generally, we like each PR to take care of a single thing. E.g.
1. docs: add "Server configuration" concept
2. feat(server): trailing slash configuration

Having both changes in separate PRs makes changes easier to navigate.

2023-06-15 05:14 UTC, deer commented on docs/concepts/server-configuration.md
if only this were in a "Contributing" section 🙃

2023-06-15 11:10 UTC, iuioiua approved these changes
LGTM! Thanks you, @deer.

2023-06-15 17:01 UTC, merged