feat: add kv oauth plugin as first party plugin
freshframework/fresh pull request #1774
Opened 2023-09-14 07:09 UTC by mbhrznr

closes #1733.  

migrates the plugin from the kv oauth repository to this one.    
tweaks some minor stuff to align with the other plugins.

2023-09-16 01:19 UTC, iuioiua requested changes

2023-09-16 01:19 UTC, iuioiua commented on plugins/kv_oauth.ts
> +    signOutPath?: string;
Let's move this out into its own `KvOAuthPluginOptions` interface.

2023-09-16 07:11 UTC, iuioiua approved these changes
LGTM! Thank you for this 👍🏾

2023-09-18 17:02 UTC, marvinhagemeister commented on .github/workflows/ci.yml
> +        run: deno test -A --trace-ops --unstable
Are the `--unstable` flag needed?

2023-09-18 17:03 UTC, marvinhagemeister approved these changes
This is great! Thanks for making a PR 👍

2023-09-18 17:10 UTC, merged