Fix fresh ref
freshframework/fresh pull request #2340
Opened 2024-02-26 10:56 UTC by mcgear

There was an issue with the tailwind error page being pulled in by ref to $fresh, fixed so now it just uses the file

2024-02-26 12:20 UTC, deer requested changes
Looks like you didn't base this off main, but rather your `build mode` branch.

2024-02-27 08:02 UTC, mcgear commented
Ahh, right. Yea, i forgot to branch for my build mode changes. I removed those from this branch, so it is just the ref fixes.

2024-02-27 08:25 UTC, deer approved these changes

2024-03-12 11:13 UTC, marvinhagemeister approved these changes
Good catch, thanks for making a PR 👍

2024-03-12 11:14 UTC, merged