refactor: rename `FreshContext.req` to `FreshContext.request`
freshframework/fresh pull request #2593
Opened 2024-07-10 16:23 UTC by timreichen

ref: https://github.com/denoland/fresh/issues/2363#issuecomment-2198660369
- renames `FreshContext .req` property to `FreshContext.request`

2024-07-31 15:00 UTC, timreichen commented
@marvinhagemeister Ready for review.

2024-08-16 13:13 UTC, marvinhagemeister requested changes
At Deno here we prefer `ctx.req` for brevity reasons. Merging this would make my coworkers unhappy. Instead of removing it entirely, you could add a getter to alias `ctx.request` -> `ctx.req`.

2024-08-16 13:34 UTC, timreichen commented
> At Deno here we prefer `ctx.req` for brevity reasons. Merging this would make my coworkers unhappy. Instead of removing it entirely, you could add a getter to alias `ctx.request` -> `ctx.req`.

Are you sure? It seems there are lot of upvotes which agree with the change (https://github.com/denoland/fresh/issues/2363#issuecomment-2203385562
I would find it weird to have a property alias just for convenience in a new public API.

2024-09-04 14:36 UTC, Atmos4 commented
@timreichen I don't find `req` weird _personally_

Because let's be real, this PR is only nitpicking and personal preference. Deep down it's not important what the name of the variable is as long as it's somewhat clear. 

I use Hono a lot, it's `req` in Hono, it saves both maintainers and lib users a few characters, everyone knows what it is, everyone is happy.

Apart from you apparently.

2024-09-05 06:11 UTC, timreichen commented
> @timreichen I don't find `req` weird _personally_
> 
> Because let's be real, this PR is only nitpicking and personal preference. Deep down it's not important what the name of the variable is as long as it's somewhat clear.
> 
> I use Hono a lot, it's `req` in Hono, it saves both maintainers and lib users a few characters, everyone knows what it is, everyone is happy.
> 
> Apart from you apparently.

I don't find `req` weird per se, I would find it weird to have both `request` and `req` in an interface when they represent the exact same as proposed by @marvinhagemeister.

But this is not about personal preference, it is about consistency and alignment with web apis.
As I pointed out, `request` as a property is present in [FetchEvent.prototype.request](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/request). Naming a property `req` instead `request` that represents a [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) simply makes it inconsistent with web apis.

What I find *is* a personal preference however is to sacrifice consistency over the convenience of saving a few chars.

2024-10-04 12:09 UTC, timreichen commented
@marvinhagemeister I think we should resolve this issue soon. I worked a lot on deno @std for the last two years helping to make the mods consistent among each other and follow web api syntax and conventions. So this issue seems like a no-brainer to me. Is there any chance it can be adopted?

2024-10-04 19:19 UTC, nnmrts commented
Apart from the consistency concerns, I think "req" instead of "request" is **also** bad because:

- Other, especially older frameworks doing the same does not mean fresh should do it. Quite the opposite actually: future developers born today will not grow up scrolling through express.js docs like we did, so it becomes increasingly likely they are not familiar with the usual `req, res` or `reg, ctx` scheme.
- Without enough context (and not "ctx" 😜) it could be confused with the common ["require", "requirement"](https://www.merriam-webster.com/dictionary/req) or for people with bad eyes (like me) even with words starting with "reg" like "register", "regular" or "region".
- Without it being the full word, it's unclear which form of the word it is: "request", "requests", "requesting", "requested", etc. are all common variations of that word, affecting the understanding of the actual format of the value behind the variable. Is it an array of requests, or maybe even a boolean?
- It sets a precedent in code bases; let's also call it "res" instead of "response" (which a lot of frameworks sadly do as well, I know), now "res" could also mean the common words "resource", "resolution", "reserve" or even "research". And why not call it "dep" instead of "dependency" (also common, sadly), [which could stand for a bunch of common words too](https://www.merriam-webster.com/dictionary/dep)?
- There are abbreviations which actually save time typing and maybe even reading and understanding code, for example "fs" instead of "file system" or the more cryptic "i18n" instead of "internationalization", but in this case, it's 3 instead of 7 letters. We are not saving any "real" time here, and also, by the time you typed the "q", your (hopefully modern) IDE will autosuggest or -complete it to "request" anyway.
- "Using complete words results in more readable code. Not everyone knows all your abbreviations. Code is written only once, but read many times." - [quoted from a documentation of an eslint rule I personally use (with great success 😉)](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/main/docs/rules/prevent-abbreviations.md).

In many of the points above, I speak from personal experience. On several occasions, I’ve had to remind work colleagues, non-technical product owners, or even my own tired 3am brain what "req", "res", "opt", "dep", "acc", etc. mean at some line deep in a codebase. And that is where you lose actual time. In our newer codebases, I introduced the aforementioned eslint plugin and code reviews are now 20% more fun (a made up stat, but I hope you get my point).

2024-12-12 10:16 UTC, timreichen commented
@marvinhagemeister I added the alias with a deprecation note. I think that way a slow adoption can happen during the alpha releases and before 1.0 is released. WDYT?

2025-03-04 03:28 UTC, justinmchase approved these changes
Yes please, also response should be on the context not returned from the next function.

2025-03-04 11:08 UTC, timreichen commented
> Yes please, also response should be on the context not returned from the next function.

Was this discussed somewhere? I think this might be better in a separate issue/PR.

2025-07-29 15:04 UTC, timreichen commented
@marvinhagemeister Would it be possible to reevaluate this PR? I hope I don't have to rebase it any longer:)

2025-12-21 17:57 UTC, closed without merging

2025-12-22 14:24 UTC, nnmrts commented
😭