docs: fix typo. added styling.
freshframework/fresh pull request #346
Opened 2022-06-30 20:40 UTC by cfex

Fixed typos. 
Reordered and simplified text.
Added some styling.

2022-07-01 12:32 UTC, aroramrinaal requested changes

2022-07-01 12:32 UTC, aroramrinaal commented on README.md
> +# fresh  <img  src="./www/static/typescript.svg" height="25px" alt="typescript logo">
Was wondering why you used a **typescript** logo here?

2022-07-01 14:36 UTC, cfex commented on README.md
> +# fresh  <img  src="./www/static/typescript.svg" height="25px" alt="typescript logo">
Hey, no particular reason, looks good combined with this:
![image](https://user-images.githubusercontent.com/24775798/176915128-d8f79dda-56b4-4cb5-ae7a-1390509f74ef.png)
![image](https://user-images.githubusercontent.com/24775798/176915169-a10899d0-39e6-49de-a40e-75b5751dc258.png)

2022-07-04 11:13 UTC, lucacasonato approved these changes
Thank you @cfex.

2022-07-04 11:14 UTC, merged