feat: trailingSlash
freshframework/fresh pull request #433
Opened 2022-07-05 19:11 UTC by fdemir

I didn't write a test for this feature, yet. I've created a new property in StartOptions called `route`. We can provide more functionality for routing in the future. 

Please leave some preview. Thanks in advance.

2022-07-05 19:13 UTC, fdemir commented on src/server/context.ts
> +      if (this.#routerOptions.trailingSlash) {
this will add a `/` to end of the all routes patterns.

2022-07-05 19:14 UTC, fdemir commented on src/server/context.ts
> +  trailingSlash: false,
disabled by default.

2022-07-05 19:15 UTC, fdemir commented
May we consider adding this option to the documentation

2022-07-06 10:06 UTC, lucacasonato reviewed
This looks good. It'll need a test before I can land it though. Another test fixture, like `tests/fixture_error/` is probably in order.

2023-05-29 22:02 UTC, iuioiua requested changes
Hi @fdemir, could you please resolve the merge conflicts and provide a brief explainer/example in the documentation? Once done, this should be ready to merge.

2023-05-29 22:02 UTC, iuioiua commented on src/server/types.ts
> +  trailingSlash?: boolean;
Can you please add the `@default` JSDoc directive and briefly document the purpose of this option?

2023-06-06 12:55 UTC, iuioiua commented
Hi @fdemir, are you still willing and able to pursue this PR?

2023-06-14 16:08 UTC, deer commented
Hey @iuioiua, I picked this one up since it seemed to be missing documentation. Opened a new PR.

2023-06-15 04:21 UTC, iuioiua commented
Closing in favour of #1291, which uses this PR as it's foundation. Thank you, @fdemir.

2023-06-15 04:21 UTC, closed without merging