typo: aligned Docs with deno-fresh-demo convention.
freshframework/fresh pull request #582
Opened 2022-08-03 17:30 UTC by moonstripe

Figured it'd make sense to be consistent.

2023-05-16 13:24 UTC, iuioiua commented on docs/.DS_Store
Can you please delete this file?

2023-05-16 13:25 UTC, iuioiua requested changes
Two other instances in the codebase mention `my-project` instead of `deno-fresh-demo`. Could you please adjust these too?

2023-05-23 20:04 UTC, moonstripe commented on docs/.DS_Store
Done

2023-05-23 20:04 UTC, moonstripe commented
> 

Where are these other mentions? Couldn't find them in the docs.

2023-05-24 01:42 UTC, iuioiua commented
Try searching `my-project`. The file paths that include this are:
- [ ] /www/routes/index.tsx
- [ ] /www/routes/update.tsx

2023-06-05 04:43 UTC, iuioiua approved these changes
I applied my suggested fixes myself. Now, LGTM! Thank you.

2023-06-05 04:43 UTC, merged