dotenv option
freshframework/fresh pull request #740
Opened 2022-09-09 09:34 UTC by beyazit

added dotenv option to read environment variables files

2022-09-10 10:08 UTC, lucacasonato reviewed
I like this. Let's actually enable dotenv always, with no opt-out in the init script. We should try to keep the options in the init script nice and simple so users don't have to make a bunch of decisions when they are initially setting up their Fresh project :)

2022-09-10 10:08 UTC, lucacasonato commented on src/dev/imports.ts
> +  imports["$std/"] = `https://deno.land/std/`;
This should be a versioned import.

2023-02-10 09:33 UTC, thorwebdev commented
Just found this while looking for docs for `dotenv`. Wondering what the status here is? Is it worthwhile to contribute some docs or is `dotenv` default landing soon?

2023-05-16 12:41 UTC, iuioiua requested changes
Could you please remove any opt-in/opt-out options, as Luca requested? I'll merge once, the conflict and my suggestion are also addressed 👍🏾

2023-05-16 12:41 UTC, iuioiua commented on src/dev/imports.ts
> +export const RECOMMENDED_STD_VERSION = "0.155.0";
```suggestion
export const RECOMMENDED_STD_VERSION = "0.187.0";
```
This is the current latest version.

2023-05-16 23:48 UTC, iuioiua approved these changes
I've added a small sentence pointing out this new behaviour in the docs. Thanks for this, @0bl!

2023-05-16 23:48 UTC, merged